name: 'AdoreMe Tech PHP CPD Composite Action'
description: 'Run PHP CPD'
inputs:
  php-image:
    description: 'The PHP image to use'
    required: true
  report-dir:
    description: 'PHP CPD report directory'
    required: true
    default: 'build/reports'
  report-file-name:
    description: 'PHP CPD report file name'
    required: true
    default: 'php-cpd.xml'
runs:
  using: "composite"
  steps:
    - name: 'Run PHP CPD'
      run: $GITHUB_ACTION_PATH/check.sh
      shell: bash
      env:
        INPUT_PHP_IMAGE: ${{ inputs.php-image }}
        INPUT_PHPMD_REPORT_PATH: '${{ inputs.report-dir }}/${{ inputs.report-file-name }}'
    - name: 'Run PHP CPD Report'
      uses: adore-me/pcpd-github-action@v0.0.1
      with:
        name: 'PHP CPD'
        title: 'PHP CPD report'
        path: '${{ inputs.report-dir }}/${{ inputs.report-file-name }}'
